version: '3'
services:
  user-microservice:
    image: user-microservice
    build:
      context: .
      dockerfile: Dockerfile
    container_name: user-microservice-container
    restart: always
    ports:
      - "19210:19210"
    env_file:
      - .env
